# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions.
# Practice demo
# for login cred- az ad sp create-for-rbac -n "MyApplast" --sdk-auth --role Contributor --scopes /subscriptions/(sub id>
name: Build and deploy WAR app to Azure Web App - demojavaspringpetclinic

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: 'demojavaspringpetclinic'
          path: '${{ github.workspace }}/target/*.jar'
          #path: '${{ github.workspace }}/target/demo.war'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: 'demojavaspringpetclinic'
      - name: Sign in to Azure 
        uses: azure/login@v1
        with:
         creds: ${{ secrets.MYAZURE_CREDENTIALS }}
         enable-AzPSSession: 'true'
         allow-no-subscriptions: 'true'
         #environment: 'Production'
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'demojavaspringpetclinic'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3BBC1DD7DDD44B6480993004351F078E }}
          package: '*.jar'
