name: Java CI

on:
  push:
    branches: [ feature/Kumar]
  pull_request:
    branches: [ feature/Kumar ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn package

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: petclinic
        path: target/spring-petclinic-2.4.5.jar
